on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: 'My first github hello world action and load of sql anywhere'
    steps:
    - name: My first github hello world action and load of sql anwyhere
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"